
INSERT INTO FUNDOS (TICKER, NOME)
WITH DATA_FUNDOS AS (

    SELECT 'BBT123', 'BRADESCO' FROM DUAL UNION ALL
    SELECT 'BBC125', 'FAC INSTITUTO' FROM DUAL UNION ALL
    SELECT 'CCT002', 'BTEFJM TESTE' FROM DUAL UNION ALL
    SELECT 'TTA125', 'ABF GROUP' FROM DUAL
    )
    SELECT * FROM DATA_FUNDOS;
    
    
INSERT INTO EMPREENDIMENTOS (TICKER, SEGMENTO, NOME)
WITH DATA_EMPREENDIMENTO AS (

    SELECT 'BBT123', 'EMPRESA BANCARIA BRADESCO ESTADUAL LTDA', 'BRADESCO' FROM DUAL UNION ALL
    SELECT 'BBC125', 'EMPRESA GERENCIAMENTO DE PESSOAS FAC INSTITUTO','FAC INSTITUTO' FROM DUAL UNION ALL
    SELECT 'CCT002', 'EMPRESA DE TETSE PARA TESTE','BTEFJM TESTE' FROM DUAL UNION ALL
    SELECT 'TTA125', 'EMPRESA DE LOGISTICA INTERCACIONAL', 'ABF GROUP' FROM DUAL 
    )
    SELECT * FROM DATA_EMPREENDIMENTO;
    
    
INSERT INTO ENDERECOS (TICKER, NOME, ENDERECO, BAIRRO, CIDADE, AREA_BRUTA)
WITH DATA_ENDERECOS AS (

    SELECT 'BBT123', 'BRADESCO', 'RUA JAJA FUI', 'BAIRRO SAIDAR', 'VILA VILHA', 1523548923 FROM DUAL UNION ALL
    SELECT 'BBC125', 'FAC INSTITUTO', 'RUA TTATA', 'RIO JOAO', 'CARIACICA', 12154834826 FROM DUAL 
    )
    SELECT * FROM DATA_ENDERECOS;