/*
DROP TABLE FUNDOS;
DROP TABLE EMPREENDIMENTOS;
DROP TABLE ENDERECOS;
DROP TABLE COTACOES;
DROP TABLE RELATORIOS;
*/


CREATE TABLE FUNDOS (
    TICKER VARCHAR(6) NOT NULL,
    NOME VARCHAR(64) NOT NULL,
    SEGMENTO VARCHAR(64) NOT NULL
);

CREATE TABLE EMPREENDIMENTOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    SEGMENTO VARCHAR(32) NOT NULL,
    NOME VARCHAR(64) NOT NULL
);

CREATE TABLE ENDERECOS (
    ID NUMBER GENERATED ALWAYS AS IDENTITY,
    EMPREENDIMENTO_ID INT NOT NULL,
    ENDERECO VARCHAR(128) NOT NULL,
    BAIRRO VARCHAR(32) NOT NULL,
    CIDADE VARCHAR(32) NOT NULL,
    AREA_BRUTA NUMERIC(9,3)
);

CREATE TABLE COTACOES (
    TICKER VARCHAR(6) NOT NULL,
    ABERTURA DECIMAL(2) NOT NULL,
    FECHAMENTO DECIMAL(2) NOT NULL,
    MINIMO DECIMAL(2) NOT NULL,
    MAXIMO DECIMAL(2) NOT NULL,
    VOLUME_COTAS INT NOT NULL,
    MES DATE NOT NULL
);

CREATE TABLE RELATORIOS (
    TICKER VARCHAR(6) NOT NULL,
    ARQUIVO VARCHAR(128) NOT NULL,
    MES DATE NOT NULL
);

ALTER TABLE FUNDOS
    ADD CONSTRAINT PK_TICKER
    PRIMARY KEY(TICKER);

ALTER TABLE EMPREENDIMENTOS
    ADD CONSTRAINT PK_EMPREENDIMENTO
    PRIMARY KEY (ID);

ALTER TABLE ENDERECOS ADD (
    CONSTRAINT PK_ENDERECOS PRIMARY KEY (ID),
    CONSTRAINT FK_EMPREENDIMENTOS
        FOREIGN KEY(EMPREENDIMENTO_ID)
        REFERENCES EMPREENDIMENTOS (ID)       
);

ALTER TABLE COTACOES ADD (
    CONSTRAINT PK_COTACAO PRIMARY KEY (TICKER, MES),
    CONSTRAINT FK_COTACOES_FUNDO FOREIGN KEY (TICKER) REFERENCES FUNDOS (TICKER)
);

ALTER TABLE RELATORIOS ADD (
    CONSTRAINT PK_RELATORIO PRIMARY KEY (TICKER, MES),
    CONSTRAINT FK_RELATORIOS_FUNDO FOREIGN KEY (TICKER) REFERENCES FUNDOS (TICKER)
);

ALTER TABLE COTACOES DROP CONSTRAINT FK_COTACOES_FUNDO; -- RETIRAR FK

ALTER TABLE RELATORIOS DROP CONSTRAINT FK_RELATORIOS_FUNDO; -- RETIRAR FK


INSERT INTO COTACOES (TICKER, ABERTURA, FECHAMENTO, MINIMO,MAXIMO, VOLUME_COTAS, MES)
WITH CONTACOES_DATA AS (

    SELECT 'SNAG11', 01, 17, 10, 11, 14, TO_DATE('29/04/2022','DD/MM/YYYY') FROM DUAL UNION ALL
    SELECT 'SNAG12', 01, 17, 10, 12, 13, TO_DATE('17/10/2022','DD/MM/YYYY') FROM DUAL

    )
    SELECT * FROM CONTACOES_DATA;
    
    
    SELECT * FROM cotacoes;