/*
DROP INDEX COTACOES_VOLUME_COTAS_IDX;
DROP INDEX EMPREENDIMENTOS_NOME_IDX;

DROP TABLE ENDERECOS;
DROP TABLE COTACOES;
DROP TABLE EMPREENDIMENTOS;
DROP TABLE FUNDOS;
*/

CREATE TABLE FUNDOS ( 
    TICKER VARCHAR(6) NOT NULL,
    NOME VARCHAR(64) NOT NULL
);

CREATE TABLE EMPREENDIMENTOS (
    TICKER VARCHAR(6) NOT NULL, -- NUMERICO COM 6 DIGITOS
    SEGMENTO VARCHAR(80) NOT NULL,
    NOME VARCHAR(64) NOT NULL
);

CREATE TABLE ENDERECOS (
    TICKER VARCHAR(6)NOT NULL,
    NOME VARCHAR(64) NOT NULL,
    ENDERECO VARCHAR(128) NOT NULL,
    BAIRRO VARCHAR(32) NOT NULL,
    CIDADE VARCHAR(32) NOT NULL,
    AREA_BRUTA NUMERIC(9,3)
);

CREATE TABLE COTACOES (
    TICKER VARCHAR(6) NOT NULL,
    ABERTURA DECIMAL(2) NOT NULL,
    FECHAMENTO DECIMAL(2) NOT NULL,
    MINIMO DECIMAL(2) NOT NULL,
    MAXIMO DECIMAL(2) NOT NULL,
    VOLUME_COTAS INT NOT NULL,
    MES DATE NOT NULL
);

/*
* INDEX
*/
CREATE INDEX EMPREENDIMENTOS_NOME_IDX ON EMPREENDIMENTOS (NOME);
CREATE INDEX COTACOES_VOLUME_COTAS_IDX ON COTACOES (VOLUME_COTAS);

/*
* CHAVE PRIMARIAS
**/
ALTER TABLE FUNDOS
    ADD CONSTRAINT PK_TICKER
    PRIMARY KEY(TICKER);
    
    
 ALTER TABLE EMPREENDIMENTOS 
    ADD CONSTRAINT PK_NOME
    PRIMARY KEY (NOME);
    
    
 /*
 * CHAVE ESTRANGEIRAS
 **/   
 
ALTER TABLE COTACOES
    ADD CONSTRAINT FUNDOS_TICKER_FK
    FOREIGN KEY (TICKER)
    REFERENCES FUNDOS (TICKER);
    
ALTER TABLE EMPREENDIMENTOS
    ADD CONSTRAINT EMPREENDIMENTOS_TICKER_FK
    FOREIGN KEY (TICKER)
    REFERENCES FUNDOS (TICKER);
    
ALTER TABLE ENDERECOS
    ADD CONSTRAINT ENDERECOS_TICKER_FK
    FOREIGN KEY (TICKER)
    REFERENCES FUNDOS (TICKER);
    
ALTER TABLE ENDERECOS
    ADD CONSTRAINT ENDERECOS_NOME_FK
    FOREIGN KEY (NOME)
    REFERENCES EMPREENDIMENTOS (NOME);
    
    